### ISSUE TITLE
Retrieve data after every iteration (feature request)

### ISSUE THREAD

**Issue by micuat** [genekogan/ofxTSNE#1]
Hi, looks like a cool add-on! I played with t-SNE for Python recently and noticed that outputting data after every iteration is kind of nice:
https://www.instagram.com/p/-fcjN3gT0f/

It seems some modification on bhtsne has to be done, but I think it will be a nice feature to add!

**Comment by genekogan** [comment]
great suggestion! this has been added as of dbe8462ddb7bc6d94f34fbfe3bd2db2ebef2cdf1
