### ISSUE TITLE
Unable to run example imagesGrid even with full path?

### ISSUE THREAD

**Issue by kyeshmz** [genekogan/ofxTSNE#10]
Hi, trying to run the example imagesGrid by copying the images that I have downloaded with the script (category: both) and placing it in the data/ of the example file.

Outputting the full path (/Users/kkshmz/~~~) doesn't work for me and comes up as no images.
I also tried the ofToPath("images/") as in the first example, but was unable to run the example.

Is there something that I am just missing?

Thanks in advance.

**Comment by genekogan** [comment]
first check: do the images have any of the following extensions?
`const string allowed_ext[] = {"jpg", "png", "gif", "jpeg"};`

second: is the number of images  > `nx * ny`.

if still not sure, can you output the console log?

**Comment by kyeshmz** [comment]
Hi,
Thank you for the reply.
The images are from the dataset, so there are around 1,700 images with jpg extension.
I have made the number of images 25, but still doesn't work

Here is the console log
```
Users/kkshmz/openFrameworks/addons/ofxTSNE/example-imagesGrid/bin/data/images/[notice ] Gathering images...
[ error ] There are less images in the directory than the grid size requested (nx*ny=25). Exiting to save you trouble...
[notice ]  - loading image 0 / 25 (0 in dir)
```

**Comment by genekogan** [comment]
try '/Users' not 'Users' ?

**Comment by kyeshmz** [comment]
Err sorry, bad copy paste, /Users is included.
Looks like this in the cpp
```
string imageDir = "/Users/kkshmz/openFrameworks/addons/ofxTSNE/example-imagesGrid/bin/data/images/";
```

**Comment by kyeshmz** [comment]
Just to update, this worked completely fine when using external harddrive with path
```
string imageDir = "/Volumes/macOS 830-256GB/test1";
```

**Comment by genekogan** [comment]
i'm really not sure why this would work fine in your external HD but not in the original folder, unless there is a typo, a permission error, or some discrepancy with how the extensions in the filenames are formatted, for example if there is a space at the end of the filename, e.g. `"image.png "` vs `"image.png"`.  if you're still trying to figure it out, try looking at the basic function ofDirectory and see if that turns up any insights. i will close this issue for now, but feel free to re-open if you have anything to add.
