### ISSUE TITLE
Images are downloaded to the wrong path "images22"

### ISSUE THREAD

**Issue by vorg** [genekogan/ofxTSNE#2]
[download_images.py#L11](https://github.com/genekogan/ofxTSNE/blob/master/download_images.py#L11)

``` python
root_dir = 'example-images/bin/data/images22'
```

[ofApp.cpp#L9](https://github.com/genekogan/ofxTSNE/blob/master/example-images/src/ofApp.cpp#L9)

``` c++
int nFiles = dir.listDir(ofToDataPath("images/"));
```

**Comment by genekogan** [comment]
oops, thanks for the catch. this has been fixed.
