### ISSUE TITLE
example-images stopping on ofxCcv::encode

### ISSUE THREAD

**Issue by sulram** [genekogan/ofxTSNE#7]
Hello there, I'm trying to run the example-images project on MacOS Xcode / oF 0.9.8

It's stopping on this point:
```
[notice ]  - loading image 140 / 159
[ error ] Can't find network file image-net-2012.sqlite3
[notice ] Encoding images...
[notice ]  - encoding image 0 / 159

vector<float> ofxCcv::encode(const ofPixels& pix, int layer) const {
  convnet->count = layer; // hack to extract a particular layer with encode *** EXC_BAD_ACCESS

```

Do you know what can be missing?
I using my own images on /data/images directory, and already run `sh setup_ccv.sh` script on ofxCvv

Thanks!

**Comment by sulram** [comment]
SOLVED, copyed the file `image-net-2012.sqlite3` from `ofxCcv/example-classify` to data folder.
What is this file?

**Comment by genekogan** [comment]
this is the model file that ccv loads the weights from, and needs to be linked to anytime you use it (in your data folder or can load it from elsewhere).
